apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 3x-ui-db
  namespace: xray
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: 3x-ui-db
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        XUI_DB_DSN: "postgresql://{{ .username }}:{{ .password }}@cnpg-rw.cnpg.svc.cluster.local:5432/3x-ui"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/3x-ui
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/3x-ui
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
