apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: xray-config
  namespace: xray
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: xray-config
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        config.json: "{{ .config_json }}"
  data:
    - secretKey: config_json
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: xray
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: config.json
