apiVersion: v1
kind: Service
metadata:
  name: xray
  namespace: xray
  labels:
    app.kubernetes.io/name: xray
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: xray
  ports:
    - name: proxy-tcp
      port: 10000
      targetPort: proxy-tcp
      protocol: TCP
    - name: proxy-udp
      port: 10000
      targetPort: proxy-udp
      protocol: UDP
