apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: operator-oauth # must be this, the helm chart is hardcoded to look for this secret name
    creationPolicy: Owner
    template:
      data:
        client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tailscale
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-id
    - secretKey: client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: tailscale
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-secret