apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: cnpg
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: longhorn
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
  resources:
    requests:
      cpu: 125m
      memory: 256Mi
    limits:
      cpu: "250m"
      memory: 512Mi
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: authentik
        login: true
        passwordSecret:
          name: cnpg-authentik
