apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-authentik
  namespace: cnpg
  labels:
    "cnpg.io/reload": "true"
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-authentik
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: cnpg/role/authentik
        metadataPolicy: None	
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/authentik
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password