apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-authentik
  namespace: cnpg
  labels:
    "cnpg.io/reload": "true"
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-authentik
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default	
        decodingStrategy: None
        key: cnpg/role/authentik
        metadataPolicy: None	
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/authentik
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-n8n
  namespace: cnpg
  labels:
    "cnpg.io/reload": "true"
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-n8n
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-vaultwarden
  namespace: cnpg
  labels:
    "cnpg.io/reload": "true"
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-vaultwarden
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        installation_id: "{{ .installation_id }}"
        installation_key: "{{ .installation_key }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/vaultwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/vaultwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
    - secretKey: installation_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vaultwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: installation_id
    - secretKey: installation_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vaultwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: installation_key