apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-authentik
  namespace: cnpg
  labels:
    "cnpg.io/reload": "true"
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-authentik
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username | b64enc }}"
        password: "{{ .password | b64enc }}"
  data:
    - secretKey: username
      remoteRef:
        key: secrets/data/cnpg/role/authentik/data
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/data/cnpg/role/authentik/data
        property: password
