apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/j6js/k8s.git
    targetRevision: main
    path: argocd/manifests/bitwarden/config
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
