apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: "0.38.0"
    helm:
      releaseName: vaultwarden
      valuesObject:
        replicas: 2
        image:
          extraVars:
            - name: PGUSER 
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-generated
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-generated
                  key: password
            - name: DATABASE_URL
              value: postgres://:@cnpg-rw.cnpg.svc.cluster.local:%!s(float64=5432)/vaultwarden
            - name: PGPORT
              value: "5432"
        pushNotifications:
          enabled: true
          existingSecret: vaultwarden-generated
          installationId:
            existingSecretKey: installation_id
          installationKey:
            existingSecretKey: installation_key
          # defaults to US region, set relayUri and identityUri if EU region is used, etc
          # relayUri: https://push.bitwarden.eu # defaults to https://push.bitwarden.com
          # identityUri: https://identity.bitwarden.eu # defaults to https://identity.bitwarden.com
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
