apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: "0.38.0"
    helm:
      releaseName: vaultwarden
      valuesObject:
        replicas: 2
        image:
          extraVarsSecret: vaultwarden-generated
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
