apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/j6js/k8s.git
    targetRevision: main
    path: argocd/manifests/wazuh
  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
