apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      stringData:
        postgresql-password: "{{ .postgresqlPassword }}"
        secret-key: "{{ .secretKey }}"
  data:
    - secretKey: postgresqlPassword
      remoteRef:
        key: cnpg/role/authentik
        property: password
    - secretKey: secretKey
      remoteRef:
        key: authentik
        property: secretKey
