apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        postgresql-password: "{{ .postgresql-password }}"
        secret-key: "{{ .secret-key }}"
  data:
    - secretKey: postgresql-password
      remoteRef:
        key: cnpg/role/authentik
        property: password
    - secretKey: secret-key
      remoteRef:
        key: authentik
        property: secretKey
