apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-ui-oidc
  namespace: longhorn-system
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-ui-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .clientid }}"
        client-secret: "{{ .clientsecret }}"
  data:
    - secretKey: clientid
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oidc/longhorn-ui
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-id
    - secretKey: clientsecret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oidc/longhorn-ui
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-secret
