version: '3'

includes:
  1: 
    taskfile: ./1-oci-tf/Taskfile.yaml
    dir: ./1-oci-tf
  2:
    taskfile: ./2-talhelper/Taskfile.yaml
    dir: ./2-talhelper
  3:
    taskfile: ./3-k8s-infra/Taskfile.yaml
    dir: ./3-k8s-infra

tasks:
  deploy:
    desc: Deploys all steps (1-3).
    cmds:
      - task: 1:deploy
      - task: 2:deploy
      - task: 3:deploy
  bootstrap:
    desc: Bootstraps all steps (1-3).
    cmds:
      - task: 1:bootstrap
      - task: 2:bootstrap
      - task: 3:bootstrap
  test:
    desc: Tests all steps (1-3).
    cmds:
      - task: 1:test
      - task: 2:test
      - task: 3:test