apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/j6js/k8s.git
    targetRevision: main
    path: argocd/manifests/longhorn/config
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
