apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra-cert-manager-config.yaml
  - infra-envoy-gateway-config.yaml
  - infra-external-secrets-config.yaml
  - infra-redis-config.yaml
  - kube-prometheus-stack-config.yaml
  - infra-longhorn-config.yaml
