apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.11.2
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        httproute:
          enabled: true
          parentRefs:
            - name: public-gateway
              namespace: gateway
          hostnames:
            - longhorn.hl.j6js.com
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
