apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomizations/infra-longhorn.yaml
  - kustomizations/infra-vault.yaml
  - kustomizations/infra-vault-exposure.yaml
  - kustomizations/infra-cert-manager.yaml
  - kustomizations/infra-cert-manager-config.yaml
  - kustomizations/infra-envoy-gateway.yaml
  - kustomizations/infra-envoy-gateway-config.yaml
  - kustomizations/infra-external-secrets.yaml
  - kustomizations/infra-external-secrets-config.yaml
  - kustomizations/infra-cloudnativepg.yaml
  - kustomizations/infra-cloudnativepg-role-secrets.yaml
  - kustomizations/infra-cloudnativepg-cluster.yaml
  - kustomizations/infra-cloudnativepg-vault-secrets.yaml
  - kustomizations/apps.yaml
