apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-db-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cnpg/role/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
