apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-generated
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-generated
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .n8n_encryption_key }}"
        N8N_HOST: "{{ .n8n_host }}"
        N8N_PORT: "{{ .n8n_port }}"
        N8N_PROTOCOL: "{{ .n8n_protocol }}"
        N8N_SSO_OIDC_LOGIN_ENABLED: "true"
        N8N_SSO_OIDC_CLIENT_ID: "{{ .oidc_client_id }}"
        N8N_SSO_OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        N8N_SSO_OIDC_DISCOVERY_ENDPOINT: "{{ .oidc_discovery_endpoint }}"
  data:
    - secretKey: n8n_encryption_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: N8N_ENCRYPTION_KEY
    - secretKey: n8n_host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: N8N_HOST
    - secretKey: n8n_port
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: N8N_PORT
    - secretKey: n8n_protocol
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: N8N_PROTOCOL
    - secretKey: oidc_client_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oidc/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-id
    - secretKey: oidc_client_secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oidc/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: client-secret
    - secretKey: oidc_discovery_endpoint
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: oidc/n8n
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: discovery-endpoint