apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-generated
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-generated
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .n8n_encryption_key }}"
        N8N_HOST: "{{ .n8n_host }}"
        N8N_PORT: "{{ .n8n_port }}"
        N8N_PROTOCOL: "{{ .n8n_protocol }}"
  data:
    - secretKey: n8n_encryption_key
      remoteRef:
        key: n8n
        property: N8N_ENCRYPTION_KEY
    - secretKey: n8n_host
      remoteRef:
        key: n8n
        property: N8N_HOST
    - secretKey: n8n_port
      remoteRef:
        key: n8n
        property: N8N_PORT
    - secretKey: n8n_protocol
      remoteRef:
        key: n8n
        property: N8N_PROTOCOL
