apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-generated
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-generated
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        db_user: "{{ .db_user }}"
        db_password: "{{ .db_password }}"
  data:
    - secretKey: db_user
      remoteRef:
        key: cnpg/role/vaultwarden
        property: username
    - secretKey: db_password
      remoteRef:
        key: cnpg/role/vaultwarden
        property: password