apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-generated
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-generated
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        PGUSER: "{{ .db_user }}"
        PGPASSWORD: "{{ .db_password }}"
        PGDATABASE: vaultwarden
        DATABASE_URL: "postgres://:@cnpg-rw.cnpg.svc.cluster.local:%!s(float64=5432)/vaultwarden"
        PUSH_INSTALLATION_ID: "{{ .installation_id }}"
        PUSH_INSTALLATION_KEY: "{{ .installation_key }}"
  data:
    - secretKey: db_user
      remoteRef:
        key: cnpg/role/vaultwarden
        property: username
    - secretKey: db_password
      remoteRef:
        key: cnpg/role/vaultwarden
        property: password
    - secretKey: installation_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vaultwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: installation_id
    - secretKey: installation_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: vaultwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: installation_key