apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: daemonset-proxy
  namespace: envoy-gateway
spec:
  ipFamily: DualStack
  provider:
    type: Kubernetes
    kubernetes:
      envoyDaemonSet:
        patch:
          type: StrategicMerge
          value:
            spec:
              template:
                spec:
                  containers:
                    - name: envoy
                      resources:
                        requests:
                          cpu: 100m
                          memory: 256Mi
                        limits:
                          cpu: 500m
                          memory: 512Mi
                  tolerations:
                    - key: node-role.kubernetes.io/control-plane
                      operator: Exists
                      effect: NoSchedule
                    - key: node-role.kubernetes.io/master
                      operator: Exists
                      effect: NoSchedule
      envoyService:
        type: NodePort
        externalTrafficPolicy: Local
        patch:
          type: JSONMerge
          value:
            spec:
              ports:
                - name: http
                  protocol: TCP
                  port: 80
                  targetPort: 10080
                  nodePort: 30080
                - name: https
                  protocol: TCP
                  port: 443
                  targetPort: 10443
                  nodePort: 30443
                - name: https-quic
                  protocol: UDP
                  port: 443
                  targetPort: 10443
                  nodePort: 30444
                - name: xray-tcp
                  protocol: TCP
                  port: 8443
                  targetPort: 8443
                  nodePort: 38443
                - name: xray-udp
                  protocol: UDP
                  port: 8443
                  targetPort: 8443
                  nodePort: 38443
