apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-ui-oidc
  namespace: envoy-gateway
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-ui-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-id: "{{ .client-id }}"
        client-secret: "{{ .client-secret }}"
  data:
    - secretKey: client-id
      remoteRef:
        key: oidc/longhorn-ui
        property: client-id
    - secretKey: client-secret
      remoteRef:
        key: oidc/longhorn-ui
        property: client-secret
