apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: gateway
spec:
  secretName: vault-tls
  dnsNames:
    - vault.j6js.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: gateway
spec:
  secretName: argocd-tls
  dnsNames:
    - argo.j6js.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: gateway
spec:
  secretName: authentik-tls
  dnsNames:
    - auth.j6js.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: gateway
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.j6js.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
