apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - upstream
  - certificates.yaml
  - services.yaml

configMapGenerator:
  - name: dashboard-conf
    behavior: replace
    files:
      - dashboard-conf/opensearch_dashboards.yml

patches:
  - target:
      kind: StorageClass
      name: wazuh-storage
    patch: |-
      - op: replace
        path: /provisioner
        value: driver.longhorn.io
      - op: add
        path: /allowVolumeExpansion
        value: true
  - target:
      kind: Service
      name: wazuh
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: Service
      name: wazuh-workers
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: Service
      name: indexer
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
  - target:
      kind: Service
      name: dashboard
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: replace
        path: /spec/ports
        value:
          - name: http
            port: 80
            targetPort: 5601
  - path: dashboard-deployment.yaml
  - path: resource-requests.yaml
  - target:
      kind: StatefulSet
      name: wazuh-indexer
      namespace: wazuh
    patch: |-
      - op: remove
        path: /spec/template/spec/initContainers/1
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: indexer-certs
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: wazuh-indexer-node-cert
                  items:
                    - key: ca.crt
                      path: root-ca.pem
                    - key: tls.crt
                      path: node.pem
                    - key: tls.key
                      path: node-key.pem
              - secret:
                  name: wazuh-indexer-admin-cert
                  items:
                    - key: tls.crt
                      path: admin.pem
                    - key: tls.key
                      path: admin-key.pem
  - target:
      kind: StatefulSet
      name: wazuh-manager-master
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: filebeat-certs
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: wazuh-indexer-node-cert
                  items:
                    - key: ca.crt
                      path: root-ca.pem
              - secret:
                  name: wazuh-filebeat-cert
                  items:
                    - key: tls.crt
                      path: filebeat.pem
                    - key: tls.key
                      path: filebeat-key.pem
  - target:
      kind: StatefulSet
      name: wazuh-manager-worker
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: filebeat-certs
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: wazuh-indexer-node-cert
                  items:
                    - key: ca.crt
                      path: root-ca.pem
              - secret:
                  name: wazuh-filebeat-cert
                  items:
                    - key: tls.crt
                      path: filebeat.pem
                    - key: tls.key
                      path: filebeat-key.pem
  - target:
      kind: Deployment
      name: wazuh-dashboard
      namespace: wazuh
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1
        value:
          name: dashboard-certs
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: wazuh-dashboard-http-cert
                  items:
                    - key: tls.crt
                      path: cert.pem
                    - key: tls.key
                      path: key.pem
              - secret:
                  name: wazuh-indexer-node-cert
                  items:
                    - key: ca.crt
                      path: root-ca.pem
