apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-secret-key
  namespace: default
spec:
  length: 60
  digits: 15
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: default
spec:
  refreshInterval: 0s
  target:
    name: authentik-secret-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        AUTHENTIK_SECRET_KEY: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authentik-secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: authentik-secret-key-to-vault
  namespace: default
spec:
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-secret-key
  template:
    engineVersion: v2
    data:
      secret/data/authentik/config: |
        {
          "secret_key": "{{ .AUTHENTIK_SECRET_KEY }}"
        }
