apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - cluster.yaml
  - pooler.yaml
  - vault-secrets/authentik-sync.yaml
  - vault-secrets/vaultwarden-sync.yaml
  - vault-secrets/grafana-sync.yaml
