apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: vaultwarden-db-password
  namespace: cnpg-system
spec:
  length: 48
  digits: 12
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-cluster-vaultwarden
  namespace: cnpg-system
spec:
  refreshInterval: 0s
  target:
    name: cnpg-cluster-vaultwarden
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: vaultwarden
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: vaultwarden-db-password
