apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications/infra-longhorn.yaml
  - applications/infra-cert-manager.yaml
  - applications/infra-envoy-gateway.yaml
  - applications/infra-vault.yaml
  - applications/infra-external-secrets.yaml
  - applications/infra-external-secrets-config.yaml
  - applications/infra-cert-manager-config.yaml
  - applications/infra-envoy-gateway-config.yaml
  - applications/authentik.yaml
  - applications/authentik-exposure.yaml
  - applications/infra-ingress-gateway.yaml
  - applications/argocd-exposure.yaml
  - applications/infra-vault-exposure.yaml
  - applications/apps.yaml
