apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway
  namespace: o11y
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway
  selector:
    matchLabels:
      app.kubernetes.io/instance: eg
      app.kubernetes.io/name: gateway-helm
      control-plane: envoy-gateway
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-gateway-proxies
  namespace: o11y
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway
  selector:
    matchLabels:
      app.kubernetes.io/component: proxy
      app.kubernetes.io/managed-by: envoy-gateway
      app.kubernetes.io/name: envoy
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 30s
