apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-authentik-oauth
  namespace: o11y
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-authentik-oauth
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .client_id }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .client_secret }}"
  data:
    - secretKey: client_id
      remoteRef:
        key: oidc/grafana
        property: client-id
    - secretKey: client_secret
      remoteRef:
        key: oidc/grafana
        property: client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: incidentio-alertmanager
  namespace: o11y
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: incidentio-alertmanager
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        api_url: "{{ .url }}"
        alert_source_token: "{{ .alert_source_token }}"
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: o11y/incidentio
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: url
    - secretKey: alert_source_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: o11y/incidentio
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: alert_source_token
