apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-generated
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: bitwarden-generated
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        globalSettings__postgreSql__connectionString: "Host=cnpg-rw.cnpg.svc.cluster.local;Port=5432;Username={{ .db_user }};Password=\"{{ .db_password }}\";Database=bitwarden;"
        globalSettings__installation__id: "{{ .installation_id }}"
        globalSettings__installation__key: "{{ .installation_key }}"
        globalSettings__mail__smtp__username: "{{ .email_user }}"
        globalSettings__mail__smtp__password: "{{ .email_password }}"
        adminSettings__admins: "{{ .admins}}"
  data:
    - secretKey: db_user
      remoteRef:
        key: cnpg/role/bitwarden
        property: username
    - secretKey: db_password
      remoteRef:
        key: cnpg/role/bitwarden
        property: password
    - secretKey: installation_id
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: bitwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: installation_id
    - secretKey: installation_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: bitwarden
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: installation_key
    - secretKey: email_user
      remoteRef:
        key: email/noreply
        property: user
    - secretKey: email_password
      remoteRef:
        key: email/noreply
        property: password
    - secretKey: email_host
      remoteRef:
        key: bitwarden
        property: email_host
    - secretKey: email_port
      remoteRef:  
        key: bitwarden
        property: email_port
    - secretKey: admins
      remoteRef:
        key: bitwarden
        property: admins