apiVersion: v1
kind: Secret
metadata:
  name: oci-cloud-controller-manager
  namespace: kube-system
stringData:
  cloud-provider.yaml: |
    useInstancePrincipals: true
    compartment: ocid1.compartment.oc1..aaaaaaaalhdsdzan5pjlh7rxw744zsbx67jsjkyrljmjhlt3oynjs6ykipzq
    vcn: ocid1.vcn.oc1.ap-sydney-1.amaaaaaayudu7syab37tlvo5ybhkc3l7rc5qyrmvynv4eplwtjr4ol4a3ecq
    loadBalancer:
      subnet1: ocid1.subnet.oc1.ap-sydney-1.aaaaaaaa7yxzslctp4ouimcc6h7qvevsvbmvhsv3yup3zhc6zajjqjmxab3q
      securityListManagementMode: None
type: Opaque

