apiVersion: v1
kind: Secret
metadata:
    name: oci-cloud-controller-manager
    namespace: kube-system
stringData:
    cloud-provider.yaml: ENC[AES256_GCM,data:uHvC0b4oLgJWhaIb83wFrAEhTdIxHwLFSw8N/rT5yuV/wDQpuYn1d0HeS2lV824fvg/aYmcFxNoDQuV/DQ++GXzstLx/wb9/MZxr5O2lSorgY1oKn2KKPf2dW9l7ZIFKavbnY1f/6UQYrjSJ4S+Pg5TcE8y8BO0mjkYmZ3BL3jPtf3AJmkHyEb4+ipsPi6EL2Lh6jS5MnqaBuKTLthQTCdA9iJ8UKC97/7Q1GWLOGhTF5Rb7RSmmoRDObd1fX4EWUeOZvE5HzYhUBr/VEXdwfmelB/wGHdtm72Cq6qVzMW0MXPqRzi7mn2XLZYPT5JzVHUUH2GtCcoGBXUAZEoISyfiv+hI2TrHhYddbN4MHfR91R5Ee0nzlQVr/bMAHdc81DpseKBfLF7VUhCGSohC7u1x8P2cBO+BC4++YQXTqQqB6yqUeDvNutq18aY19N5s8ScH4TOVYjLMeqMgJNHdyT5pr7M3aU3t5CpjuobQiww==,iv:BNbTMvAfR56pMg0vcZJmNPdTFWDYALMEfB89AipxS/U=,tag:43FYYpBiIYo57kRp28dYrg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1pq1jtse743c4unv25smfy759wm5vuqj3fqnqxla9ynz6u4c9vulgl24f29s4xwjqsspxzat27t5a8924laeqf9r2uehqcquhyjxggft7jljrt5asyckslyp6dx2zvg8p0np2ma0ffwhwjfps7vfvczsz7jx84y3v96jfn95qf7yykgzyjacdz0yvn9hz0xdvf3yvcamwatc28k3djam6x8a4e5lazz5lpahhs3ucmy566n49dasfm4k4fzuhc9q33jkuqkz2cuvfhsgxpcrg48djpy3gw0rfv4a9e4u7mh6zxzgzlr9z2scn9ca6pc82fsyy7hlepe4mxcd33q8hqx9tsrk5vhqcq8jzxuen664ty7v90u3yg0ue3uvpg7vqyt09mgrj7q2z34uzj8lf9z7j0yusythg4nzwww20r6v7s4vxvnpufpgphg8n4n7zgm9tpj8fvxfeuwy47uyyj2lvv6k489qnj9hp5qpzrl9vs7x0yxtkzjs4m9c98aygw6x0r45gmvh8t9gkskxj64y640y4lqtjydmg506jgq546x9r53gk5smv94r9p464fc0d6t528pjr4k2zd8f243hvukwelwyvys2y88tcf4528ycjzqdh0nzm0lsr2453r3nhqsrhg3trda2p0an8zvsvu7jgqhqq6gwwexzdyzftwp4x52faz0cyq65uj5ym0uxh06m59lvyayyevnrknpp4e3fpyn80fw9xaj2pz4z74kptlgekkztk3xv3y2q47mzhxp8x48kjz42yv26rfgefx34k9n6lpekn2gfw82vefg9nk4f24j8u7pycfg7c856ggjp8e90vtreup7k544yk6c3xl9r04c2tlnredhmka9dqyknkfzmlamx0fu5pq7nqkvdkysfrqvft8rrjw4yxel4zwd9nnr9uy98f36ggaz4ah3yvq80ctcsux5hdu47vzz5alqjhn9c255ag65c5mrwpfzgak5xcplcxsrzxp97l6a5mna4sw982pzm5atx9scy7hz752ju56g2hzm3fvv8kqeggxq0f4thha5m27tssg805vctzydf4dnq35f8j0c38n64dy4k4xwfv6rxp9juysgscr58sjc629j6x5ts9cevdut2q8g9uxps8pngetg9460hcc5rcg8fs29h9gsp44fj22cz9y0m8twkcs0k08y5992rjk3xfckvn07fqkxp45gmsspgednhna33cve5rdglzp2fdeq470pyqu2wshmk6dayq2wxaq7ra04zsrcgqcee93j4vuvmpm3n463u22rlxu26hj8kd0qug4fj5u4rdw68gdg27u7kz95eg3tgerj2npw4j2625qshmyq7twqrmvusggj33nhnwy87z43yv5dglp0eknfj5yhf77ptjqt362ycj48q9u45f9d9j267uhzgjdfsch8ghvt5zd0rcsc9ldv9rttxkctkwkdv9vutz9ch2fupws5ezdumg6qrwyz7cmpx8pg290cekrx6srpw0fdghymmgc3a2kkpf74h55g2sm2mcgzcp22q9qqtcnkpghepqawmat9ztgnpcfq6rqmnkv4dejzyad834zsycsjen8v3tsxs9y2pwwej8zcrllejraeqcejxv9ytk5gllj5sugqyxmhz2qg640q62enc4du23y5v00fe3pamr3zhgxykc7ekhtdz3hxnznguw94s83wu6e9ex2jrma04dty7cdwvdxwp22e3hx63fqlrxq72k6manq4gldqr8sg63qy23gdr9rcepvxns2495ggndcfgg3guvttkc3glqdv8ww564c288vv7vm0z3vcktur4ntl4r74yssuc8m9empr9d0647f9yd8rcdsjh9zzy7epfc3uxhwscf2qfx7unltm3pdv3e3t47yzdgf8qt3phlv0gtxh88h65wyaqwd04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpyK2ZMck1K
            MHkzWEF0MkJ3L1hQUmFHSWpXUmdJWXRLVXlTdDdMZjVJdHphMnF6N1pxVDNLRjRn
            NUlIOHhoaHdYVDdzS3JFa0ZnVnVldjVFZTB0RjRXRkZqbXVaak12bVpOMDI0bk9q
            QVp6Uy9EelduZzF6bisyUHBCVER3YXp1TDZ6OGFFbGMxaDN3ZFdNSXlYRktWZDYx
            eUM5NFNLVUhrWGQrNTBGUG1tUzZiRVFRL1g3UEZoL2UwcGZaY25yZjhNc3pZdGti
            Vmx5cEZwYmZBWDR4dDZwN0RYVFhCcCs4d3pyK29tU0x2eUtiajAxZVoxWWs3NUly
            ZlFlWC9TeUFJZ3pqZWI2N0JFMU1uNXQ4WC9BSExNTHBMRk12SjdUMVNjYU1BUURS
            VUhpT3V1Qk9MK3hKZWlaZ0czblBIZyt0RnFMS1ZlR2pEaWxhT0xnbnRyTUduRXVl
            eVVXQlBQb2ZKaHpxSWtSVWw2NUs1TWVXTkc1K1Z3NUthM3k4c3FuM0JiUXZHaHZq
            b1E1cFprQWYzQjZNbkZBRlNyYmFOQU1YdVFNWDBqY0xJM0hJSjRPK1F0NzhpWVhw
            WGtGbXQrNjhNRitvZjFIZUZFL1IzUk9wQVdBWnF0T0dpUTZjZnQrb1VreDd2L2J6
            aW1VN2o4aGRQUGJackFPb3czSU9iZWRhNHE4RW1xV2pMZUNYMnNkRmZYcnd0N20v
            ME5HZUZnZ0JDZXdUaVI4Rm1PUlJ1aGZmSHpoYTlQVWRpYjFoOXRIWE0ydmZLcUJG
            azI1ZGE2SnlEOG9CNWFBOGU5MTlBZHdNN0J5NzJXMjRMSFdBWEpha2EzeXlHaENh
            dndUaGc4MnJpaEszdkRpSWpkbkNwRmlhTlV2VXIrK3FUMDFraHdIZ2kwRGlDK25x
            SHF6akdIQTJrZGJOL3NuUDhyNmc0T2tGdE0xS01XT3l2M3JQdEZWY2w4WkIvMzFw
            L2NOMkZGN2ZoNXdzdEtkZnJwT085NGZmdFN4L2pENm9zN0pwV2o5WjAwSElUcVo5
            TEhRVG5WTUFuRDg5cmJDVFNQSFAzTzkwNEpjY1RTSk1hem1kRVJpY0d1dHJCRTRY
            aDRwaFJua21qVmxtMmVJWHJUNTA5WEJPaUNBT0VuNDQzY3dSY01TeGxUbkZPN2FS
            bFd5NUxLckZvU2krWXEvOUtJSFZlMUVxMlJROGVOWHpNc1F5OExkZTJJOU1jT0Z1
            a2EzNGFqdjhKaktRMC9ITHYyUnUxS0JidGZhRWlmVDhoSDZjTkxNWWd1M2t3VkRj
            UzVwS090M1ZmcGc1LzBRMXhPSTA0Rk9KdXpOOVJyN3dSTFJ6TStyRE9MUHBpZjBa
            ck94cTVXUGFjV1htOTFKOG5Md0l1dG02bTIwS3ZJLzVHeGV4cDAvYzFaWU1vSkky
            cGdlVVNzWmkwZm9QYTlPUzRuMVpWS2NuRkZiaHdhT3dVeUZGL0MrSDUvYVZQeDVx
            c3l5T3VDaXJveDZ4bVJNbjYwam5hdDlUbHBTSUJMQ0swWXhpV0FJVXpwc21jSE05
            ZGJyUjFzVGNrb3JZbXVwamNON2VmZ0VvT0dJdmQwZE9OOEFvaGZDaHZRZkJobHpF
            MmNkaDluSHNNejEwN0g1VjZ5K1JXL1VJeVhLbVRLWGdEQjJqaTl3SjlSV3dXNDMz
            Y045bFNnNitKaGZDVUt0T3hKMnJvL2RSU2hWTmtXYmpTQzk0V3pQWEdsenhOWHVI
            ODVDQXJuTnRvVVN2a3NDbnBubHAyd1BMM2xjNC9DTGxROFB5SURaREYxYzNQTUJT
            WmVSZW1iZENTOHA5WUhueVZINFphZmJ5azJEemFWdXkvTGFFWDkvdXZVT2FwWEt0
            MDd5ajdVaUFUb05xcUNDMDZ6bG5oYWdpSTkzWEdyR3VNcEgwZ0NMd29RZE1YUWx4
            c1BLazh1aWRMZDR0ODZSZGlrQ3V4dkxNa2JabUJ1TU03eDE1dGpSS3BkaXhFZwpy
            OVJ0RjRMcXQxbnJQK2QybDA4UW45YkhPOGYvc3cvYklSUUJ0UGl0cUtNCi0tLSBM
            dGJKUVlyTHFqMEpnMUtOZ1V1R0xhQ01OMFRMeTBtTlpwcGVCaERNWGNzCrS3RMMV
            1Dg8nol2MoNwhG7Fy3gh1H6dukNEq5Y9vfIux7hucOGuNYNl0UD1VzPZeDge0KUl
            ly+e8WAlapnC/dw=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pq1rzy8lst43tv3hsn0n3vdj4djvkeukw8g2u3r2l9ulzd3kudkzp9409fghclwgpfl2j5jtaf8wcat7a262hd9y8746vs24sssmgr4ktg22yzlrgzggpgp8pat3vss8mw9xxwg9x0erdzs4fq4j4yel44h0ujg23k092f0vv2t8luuxpzx4slyqvedf9v2unpwd77gm0xm4wyaym77r24zpv5u96p35l2jwehhgckq6w8wsg6dpn4sq2t4gsm5h2agrn8ng3u93ajhy3a954uaxqf69fh0jz2552py6ux99gm8q08rv2mq9d24q55vt52er67sd3v7eggysqvs37pv04kcqvsfy3v33zpku2672g3jmqpuddjg8nr52ylj7fqrhpqhza2ptlngntd5wu88mzx8y9fs6hwzh6kpv6yjx29wypyx70uxd8sgkgsn5a7wufrzxpz4wcsrk0rmkrcqkaw75vq22p9p4yyhy2w2v9uksvp5z7h9qdgzqxz4lc7kvsaash09rw0eju9xpupytz3ekmqnym0x5psrtux9fgj95h062fuc8d6w7qx3hadwt5kfek5x4zza0xuenz6jtfjwz696vg8m2dlkhqg2eryshw4rxa2grmgspcahctw2cg826gfukqrny2cnksnff232gjh72wp9a0qzc6lxzv4vkfcejvqetv5np5s98g0jyc0ntgpqkcmmvfarml5thmp88xyhk3em5yx8c943vsxr38ye864u2zgcwsf49seas59vn9t8kpfwgw4scyqj73uk2ncxkeu9gm06fdt8t35z27c6jcjmvsyvvhwkjupxd89ue5c83qg6aujmjdt9sqhsxzewgv3q3yguuzhvej9x0djc0fzy0z2z8q9h8u65yjjlxxuq7qwjm4fsf24rfvw3wxt30nursel657fpz5g43cx3d9zltrxk6yf3t432c6ey5glsx9055g33k422xvwyevfrwljzv098nw0ruq7ch3amxtu66zk3czlehthh80z0mx3v24c83e3yfxcq30yd33vfrpe59vkfvwgjschwy0ssjvf6flzk9nfye26yel24wepduk4pqjgcrgpg3lmenhes2aequ7mw46wv05ezhhn22gvfywht25sxmamza2f93gfshrtansxk7js66vzs3g7vl8dyk8alvnas0ghqpvvsvn98q83pkzu9v3l5s95e7ugqs254me2jjty3vdkkhzn047zxga6gghj58vuyt80u3ff58s9jxkkvwzp6q69xnsqssg2spgjl5qupc7thdp38wpasj7uu0uglgcjgrrlq5tnxjv4fev9n6valuqj62jf4fyqktpnnkc03zwxdzrsm2r753q2hc8mmz4m48kujrnjf5cjkz3d3h2ceufl4vzgu3kdtk0qppvlschtety4ecgjft99v6ymtgqnssept7cwjtey8azs938uhxudzxx5wpppf7xn6u6yzmtpjhd039q9avxptemyxpv638mfjdsuyrfap3g3np566kfyxcv2gcue29fmtl9w3xa3zc3fjarahpm685rdew4nrkwqkjnznf0yytypjtyrg4vznad98z99f2zaxh3y3hwmeyu5pdafszmpn4kagdya2pjmh6snydnzrt3jcau0jjwvwtn7kdf4v0pslx9t3r3vygvj0rtdfess2c4yj60dprqa80q7nkr0rhfgcjwjtyy9zsc6xfx9qxag9y56lghzcq4ng5f85z5959stv0pzp69asdycr4cd35h3hzev5655dejr30vqpcyuer7n7zkrl764z7jslq9npyd9nte50kqnunsvqhjmx9sv6l9exsy574hfk0zxn2dcm9jpqp00fcsuygr0t76usx3yjse5jerl9nqlg35pjg3upcsvnnwucdng80g8r4c0gp375xkaczqzhy0ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDdYZENzaHBL
            MEhpd053cGgyWVpvb2hVRlQyL1BvMTFGeTVxMGFnZWNGN3JONk5FZWdTRU4yWlhv
            MS9aZlR4N3hiTHAyVEtHMTBvU1ppa2Jna0crVmI5YkRRQlJpY2gxUCtwQVhOeWEr
            WVJFSGRCT01MQ1FOTzdQcnpENnVvRG9WTkxRVFdOSkZWUllrMm9pZVAxdlVteC9P
            VjZyU0V4RDVBcUFLc251Z0pCRnhLbEtvTU10TGwwcFI2RHF0d3R4MCtuNEFVVFBl
            bTBsaFJDanlSOUQwWTFqTGxWQjdCTC9OUThUZXE3UFE1T3oxRFJDT29iSGZ5ck1u
            dGdUZnAycFFtaHdMVDg0MVhXT0FSWnZHUDlOYWdRMlJWZkszREtCY1VNNWlTNVQv
            K0ZQeWxOUEVyMzk0NDRJUGZCdWp0LzBkYllyaEpIelVCRW9jZGg4MUpIVUFDRll3
            V0ZQNndBdmoxUDg1Y2RST3pNNmx1U2k3c29vcVpEbExiRGtaaU14Wkl4U2JORVR0
            cEhySlczL1ZyMlRkQ2dzRk4vZXdBNUp4RERacDZMM1BvbG9WNU1XSzFSS1B0cXh5
            dzE4cUNxWVY0U3dsVmxzdmdJdEpEWWtQbi81Z1ZIbWdmK0pYVGtjYVZrVzlsRFEx
            NmtFYjd4M2dYMDUweFRITnFBRzFsVFBWM1RwZ3grc1d0UEQzTXJNZklJanB3ZVA4
            MkJlT0lNRE9BeGJNcnFhQnVsczd3VlBLa2VrRHB5OE1QQlBpM244RXpBNkR6cFRt
            c2RkQzM5eUlXMTZnNDQ0Q1RkeERFRFVvb0grUnJWWFVXNXlnb3U3ckFOTUlJWnd2
            SDR6Wm5kcTB2VjZoeEl6STNGaUtpTWFOT09BMkFGWjJkSElldGJMK0ZFUTlpY09w
            MCtxUjVORTNzY3o1MzFvVXdPNGozMy9TVUZKNSt1L3lnbkNNYlg1N1p2MkhCVWlr
            U3BRLzRJbndpMkE5WTNUTXBqZWpRalJPOHM1dEVXN21ST291Q2JyS2UxeVFReDBx
            TXB3VEJkVGdkUlV1dW50OVRBM3pqeGMrVUNPaXBlMElhN3EycXZKOUp2TjNWRnky
            WEVGY2s0SElSRWRiUUpsQ21vYVI3eEdWYy8yQWtydE9tNm5nZ3hPSjFxVmhvT1J2
            Y091NDBEVkRtT1dMNW02blZ6MVpOc0tSN1ZpMEdjOXI1QmwxeVY2VC9XWlhLK1NG
            RmxIdmxHRnlGdi9ubmFIMGFtTXY1ZFdraksxVmhaYlB2aUlZRG11NlRrSWo3NUll
            Z2tuT09FM2hKdVJBSGZQMGh6LzVkcXBqWEpILy9LODYvRlpXbDl3NVMxQjZVUXRD
            YmZMZmxjb3Yvdnc1bVNBYUpQSFVLRlRkYklpTnhyRGJrNjhodVY1dmVsRkpKcVpQ
            STR6d1dXc1JVR05MOFMrSXBDRnV6bGg3eVBSVDVTN1JhSCsySml5bkZHREJKK2JB
            OUxtTWdoUWUzR3Y0ZGpoNlJkdm5TZFFmeVhsRG5YUGdkbzlFYXYwQlllTXVBV2RO
            cDZiNzhUc2pkbTBqWnF5NjFoK0wwTWRWMllpWnZmUFpEOU5xRmM0RG91SzRhYmhZ
            bHN5ZDNPVlVsb3dPOWlDQjYyVkNQdEZCVlEzTHZWQit1cGZSK1o4bkQvQVhvRmdO
            T2JSdXdnVk9tZDZiY0c2cFNaZ1R0S21IVzRjbm5JMVd6M2VyV0J0Nm0rdER4alU0
            cm1PYTgwalJFbFZ6MVA2L1N6ZHM4czNxSFZrdFJDMDNtb2F6S3d5RkVqemdOVEIv
            QVJYRk92UWpiVDZyZUlBVnBoTDU4K2NzNFdRUEpqSTZFMmxOUFhwRmpFUXhtUWl4
            UVNmekM4RXc1VTV1R0VrTjVKbzlIKzlOMGMrV1BSRnNtQkZycmxROUtZQ2UvUkw2
            MlJyVEZsdkhNck1ndVVsdkd5ZzRBYmpYbW03RlZjdG94ZkhJa2J3ajdFZVhLQQp2
            a2NxUVpLT2x1LzVkTnRrUHdQaXh1eFdtaFRDbjBIMGtod05kbUtpK0c0Ci0tLSBN
            M2wwVW9QbDFrSy80YXVHK2hkUCtXRVIvS0tya01XcXlGV0ZPUnVVdGZNCqL7a9Qe
            pxipVRuSzShBYY98uoCBxpkFaXPFENJszbDprADc8DWkBprvTjVbNwh29JtvI462
            Aa9yM/gAxd/wyI0=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13npvzujyqxsmmalwulncx07v9hm75zkzj25m9s03k37wh24ggsls9jl7j3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZY29JVGJnM1dKOXZ5NFAy
            UkVweG9IdUpZTUFKUTV5WmxPbGMyOGliUkhrClVwdXo5ZlRUVlJNN1RJMThLbjNO
            UVBEUVdEOUk4SWFkZ1lEclhpTWcwQVEKLS0tIGoxSzFKVnZKaHk4RVMrdG1TVDdH
            Mmw0Z1RldnN0OTg3U2ZVT2NVbkt3WWcKiqh9zPMdscP/xhP0jtcg6y/8+fS9hkMa
            Lv5fxxAPrZ+8jvp+L2B0iU67ZWP8T5QnzGDTaxeq4uahcGt3Z2l71Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T20:48:45Z"
    mac: ENC[AES256_GCM,data:ch/PxTNszaDKWyIXuRRNiCo3eAfM8Tek0ioQHGwgD/BOEWffeHdAkjkMqzvpnO5O/wpf+s6FW2yQzIUH5KNMKwFUc8MD7iJDN6gLxrEZb+aueELUPb7hM958EJA0sApH8XH/PqwrJwiaj0Aw8qd2VJ+g8wmQ30ImNd47eqRMXoI=,iv:V6nPzETfTOcuKMxOIMOxkG0NUJlKQI3mTa/q/faXlbI=,tag:E3LwslR+W0U3JwIxVGXbkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
