apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-exposure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/j6js/k8s.git
    targetRevision: main
    path: argocd/manifests/authentik/exposure
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
