apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: "2026.5.0"
    helm:
      releaseName: authentik
      valuesObject:
       authentik:
         secret_key: "PleaseGenerateASecureKey"
         error_reporting:
           enabled: true
         postgresql:
           password: "ThisIsNotASecurePassword"
       server:
         route:
           main:
             enabled: true
             hostnames:
               - authentik.domain.tld
             parentRefs:
               - name: shared-gateway
                 namespace: default
       postgresql:
         enabled: true
         auth:
           password: "ThisIsNotASecurePassword" 
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
