apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: "2026.5.0"
    helm:
      releaseName: authentik
      valuesObject:
       postgresql:
         enabled: false
       authentik:
         error_reporting:
           enabled: true
         existingSecret:
           name: authentik
       server:
         route:
           main:
             enabled: true
             hostnames:
               - auth.j6js.com
             parentRefs:
               - name: public-gateway
                 namespace: gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
