apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.32.0
    helm:
      valuesObject:
        injector:
          securityContext:
            container:
              capabilities:
                add:
                  - IPC_LOCK
          image:
            repository: hashicorp/vault-k8s
            tag: 1.7.4
            pullPolicy: IfNotPresent
          agentImage:
            repository: hashicorp/vault
            tag: 2.0.1
        server:
          image:
            repository: hashicorp/vault
            tag: 2.0.1
            pullPolicy: IfNotPresent
          securityContext:
            container:
              runAsNonRoot: true
              runAsUser: 100
              capabilities:
                add:
                  - IPC_LOCK
          logLevel: debug
          dataStorage:
            enabled: true
            storageClass: longhorn
          standalone:
            enabled: false
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true

                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                }

                storage "raft" {
                  path = "/vault/data"

                  retry_join {
                    leader_api_addr = "http://infra-vault-0.infra-vault-internal:8200"
                  }

                  retry_join {
                    leader_api_addr = "http://infra-vault-1.infra-vault-internal:8200"
                  }

                  retry_join {
                    leader_api_addr = "http://infra-vault-2.infra-vault-internal:8200"
                  }
                }

                seal "ocikms" {
                  auth_type_api_key = true
                }

                service_registration "kubernetes" {}
          extraEnvironmentVars:
            VAULT_SEAL_TYPE: ocikms
            OCI_CONFIG_FILE: /vault/userconfig/vault-oci-kms/config
            OCI_PRIVATE_KEY_PATH: /vault/userconfig/vault-oci-kms/OCI_PRIVATE_KEY
          extraSecretEnvironmentVars:
            - envName: VAULT_OCIKMS_CRYPTO_ENDPOINT
              secretName: vault-oci-kms
              secretKey: VAULT_OCIKMS_CRYPTO_ENDPOINT
            - envName: VAULT_OCIKMS_MANAGEMENT_ENDPOINT
              secretName: vault-oci-kms
              secretKey: VAULT_OCIKMS_MANAGEMENT_ENDPOINT
            - envName: VAULT_OCIKMS_SEAL_KEY_ID
              secretName: vault-oci-kms
              secretKey: VAULT_OCIKMS_SEAL_KEY_ID
            - envName: OCI_REGION
              secretName: vault-oci-kms
              secretKey: OCI_REGION
            - envName: OCI_TENANCY_OCID
              secretName: vault-oci-kms
              secretKey: OCI_TENANCY_OCID
            - envName: OCI_tenancy_ocid
              secretName: vault-oci-kms
              secretKey: OCI_TENANCY_OCID
            - envName: OCI_USER_OCID
              secretName: vault-oci-kms
              secretKey: OCI_USER_OCID
            - envName: OCI_user_ocid
              secretName: vault-oci-kms
              secretKey: OCI_USER_OCID
            - envName: OCI_FINGERPRINT
              secretName: vault-oci-kms
              secretKey: OCI_FINGERPRINT
            - envName: OCI_fingerprint
              secretName: vault-oci-kms
              secretKey: OCI_FINGERPRINT
            - envName: OCI_PRIVATE_KEY
              secretName: vault-oci-kms
              secretKey: OCI_PRIVATE_KEY
          extraVolumes:
            - type: secret
              name: vault-oci-kms
          initVolumeMounts:
            - mountPath: /vault/userconfig/vault-oci-kms
              name: vault-oci-kms
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
