apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: ghcr.io/prometheus-community/charts
    chart: kube-prometheus-stack
    targetRevision: "85.3.3"
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        prometheus:
          prometheusSpec:
            replicas: 2
            podAntiAffinity: hard
  destination:
    server: https://kubernetes.default.svc
    namespace: o11y # Observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged