apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway-fabric
  namespace: kube-system
spec:
  install:
    createNamespace: false
chart:
  spec:
    chart: "oci://ghcr.io/nginx/charts/nginx-gateway-fabric"
    version: 2.6.0
    values:
      nginx:
        service:
          nodePorts:
            - port: 31437
              listenerPort: 80
            - port: 30478
              listenerPort: 443
  interval: 1m0s