dns:
  baseDomain: j6js.com
versions:
  talos: 1.13.2
  k8s: 1.36.0
  cilium: 1.19.4
  external-dns: 1.21.1
  argocd: 3.4.2
argocd:
  repoUrl: https://github.com/j6js/k8s.git
  externalUrl: https://argo.j6js.com