apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-db-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
      engineVersion: v2
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/authentik/db
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        authentik-secret-key: "{{ .secret_key }}"
      engineVersion: v2
  data:
    - secretKey: authentik-secret-key
      remoteRef:
        key: secret/data/authentik/config
        property: secret_key
