rules:
  - name: nlb-backend-tcp-traffic
    description: "Allow TCP health checks and traffic from NLB to backend services"
    direction: ingress
    protocol: tcp
    ports: [30080, 30443, 31514]
    source: internet
    destination: ""
    for_roles: [cp, sh, wk]

  - name: nlb-backend-udp-traffic
    description: "Allow UDP health checks and traffic from NLB to backend services"
    direction: ingress
    protocol: udp
    ports: [30444, 31515]
    source: internet
    destination: ""
    for_roles: [cp, sh, wk]
