# vms.yaml : Define VMs to be created by terraform
# type: [cp, sh, wk] # Control Plane, Shared (cp + wk), Worker
# cpu: int # Number of OCPUs/full cores, vCPU is double the OCPU count
# ram: int # RAM in GB
# disk: int # OS Disk size in GB
# region: string # OCI region to create the VM in, e.g. ap-sydney-1, ap-melbourne-1
vms:
    - name: syd-sh1
      type: sh
      cpu: 2
      ram: 12
      disk: 100
      region: ap-sydney-1
      fault_domain: 1
    - name: syd-sh2
      type: sh
      cpu: 2
      ram: 12
      disk: 100
      region: ap-sydney-1
      fault_domain: 2
    - name: mel-sh1
      type: sh
      cpu: 2
      ram: 12
      disk: 100
      region: ap-melbourne-1
      fault_domain: 1
    - name: mel-sh2
      type: sh
      cpu: 2
      ram: 12
      disk: 100
      region: ap-melbourne-1
      fault_domain: 2