apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-db-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-db-credentials
    template:
      type: Opaque
      data:
        POSTGRES_HOST: "{{ .host }}"
        POSTGRES_PORT: "{{ .port }}"
        POSTGRES_DB: "{{ .dbname }}"
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/cnpg/vaultwarden
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/cnpg/vaultwarden
        property: password
    - secretKey: host
      remoteRef:
        key: secret/data/cnpg/vaultwarden
        property: host
    - secretKey: port
      remoteRef:
        key: secret/data/cnpg/vaultwarden
        property: port
    - secretKey: dbname
      remoteRef:
        key: secret/data/cnpg/vaultwarden
        property: dbname
