apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cloudnativepg-cluster
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 30s
  timeout: 5m
  prune: true
  wait: false
  path: ./k8s/infra/cloudnativepg/cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-cloudnativepg
