apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authentik
  namespace: authentik
spec:
  endpoints:
    - dnsName: auth.j6js.com
      recordType: CNAME
      targets:
        - hl.j6js.com
